version: '3.1'

services:

  service:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - ./settings.prod.conf:/var/task/linkdump/settings.prod.conf
    ports:
    - 8080:5000
    links:
     - redis
     - db
    environment:
      LINKDUMP_SETTINGS: 'settings.prod.conf'

  worker:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - ./settings.prod.conf:/var/task/linkdump/settings.prod.conf
    links:
     - redis
     - db
    environment:
      LINKDUMP_SETTINGS: 'settings.prod.conf'
    command: flask worker --processes=1


  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: development
    volumes:
    - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432

  redis:
    image: 'bitnami/redis:5.0'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
    - redis_data:/bitnami/redis/data
    expose:
      - 5432

volumes:
  redis_data:
  postgres_data:
