version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: development
    volumes:
    - postgres_data:/var/lib/postgresql/data
    ports:
    - 5432:5432

  redis:
    image: 'bitnami/redis:5.0'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
    - 6379:6379
    volumes:
    - redis_data:/bitnami/redis/data

volumes:
  redis_data:
  postgres_data:
