"""empty message

Revision ID: 1c4c14283297
Revises: f5cb90899ba5
Create Date: 2020-03-07 19:00:30.501694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c4c14283297'
down_revision = 'f5cb90899ba5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('feed_is_public', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'feed_is_public')
    # ### end Alembic commands ###
