"""empty message

Revision ID: 43606b03c16b
Revises: 1c4c14283297
Create Date: 2020-03-08 12:18:49.861822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43606b03c16b'
down_revision = '1c4c14283297'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('body_plain_text', sa.Text(), nullable=True))
    op.add_column('items', sa.Column('source_response_raw', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'source_response_raw')
    op.drop_column('items', 'body_plain_text')
    # ### end Alembic commands ###
