"""empty message

Revision ID: 2a6020e38d36
Revises: 41be25094828
Create Date: 2020-06-13 14:26:40.976196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a6020e38d36'
down_revision = '41be25094828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('twitter_card_summary', sa.String(), nullable=True),
    sa.Column('og_title', sa.String(), nullable=True),
    sa.Column('og_type', sa.String(), nullable=True),
    sa.Column('og_url', sa.String(), nullable=True),
    sa.Column('og_image', sa.String(), nullable=True),
    sa.Column('og_description', sa.String(), nullable=True),
    sa.Column('og_site_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_social_meta'))
    )
    op.add_column('items', sa.Column('social_meta_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_items_social_meta_id_social_meta'), 'items', 'social_meta', ['social_meta_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_items_social_meta_id_social_meta'), 'items', type_='foreignkey')
    op.drop_column('items', 'social_meta_id')
    op.drop_table('social_meta')
    # ### end Alembic commands ###
