"""empty message

Revision ID: 41be25094828
Revises: 43606b03c16b
Create Date: 2020-03-08 13:40:05.713257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41be25094828'
down_revision = '43606b03c16b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('item_body_plain_text_idx', 'items', ['source'], unique=False)
    op.create_index('item_source_idx', 'items', ['source'], unique=False)
    op.create_index('item_title_idx', 'items', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('item_title_idx', table_name='items')
    op.drop_index('item_source_idx', table_name='items')
    op.drop_index('item_body_plain_text_idx', table_name='items')
    # ### end Alembic commands ###
